package javax.swing;
import java.sql.*;
import javax.swing.*;
import java.awt.event.*;
import java.awt.*;
import javax.swing.table.DefaultTableModel;
public class Home extends javax.swing.JFrame {
Connection conn=null;
ResultSet RS=null;
PreparedStatement PST=null;
Statement stmt = null;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        conn=MysqlConnect.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        regjava = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        regvb = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        regora = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        regphp = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        view_count = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("COURSES OFFERED");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 30, 240, 32);

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 153));
        jLabel2.setText("COURSE NAME : JAVA Full Pack");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 100, 250, 30);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 153));
        jLabel3.setText("Fee : 12,000");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(56, 141, 130, 21);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 153));
        jLabel4.setText("Duration : 3 Months");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(56, 166, 150, 21);

        regjava.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        regjava.setText("Register..!!");
        regjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regjavaActionPerformed(evt);
            }
        });
        getContentPane().add(regjava);
        regjava.setBounds(56, 198, 120, 25);

        jLabel5.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 51));
        jLabel5.setText("COURSE NAME : VB.NET ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(356, 110, 180, 18);

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 51));
        jLabel6.setText("Fee : 12,000");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(394, 141, 90, 21);

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 51));
        jLabel7.setText("Duration : 3 Months");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(394, 166, 140, 21);

        regvb.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        regvb.setText("Register..!!");
        regvb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regvbActionPerformed(evt);
            }
        });
        getContentPane().add(regvb);
        regvb.setBounds(394, 198, 120, 25);

        jLabel8.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 153));
        jLabel8.setText("COURSE NAME : Oracle");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(56, 270, 190, 18);

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 153));
        jLabel9.setText("Fee : 10,000");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(56, 303, 100, 21);

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 153));
        jLabel10.setText("Duration : 3 Months");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(56, 328, 150, 21);

        regora.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        regora.setText("Register..!!");
        regora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regoraActionPerformed(evt);
            }
        });
        getContentPane().add(regora);
        regora.setBounds(56, 360, 130, 25);

        jLabel11.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("COURSE NAME : PHP");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(359, 270, 160, 18);

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("Fee : 10,000");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(394, 303, 100, 21);

        jLabel13.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("Duration : 3 Months");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(394, 328, 140, 21);

        regphp.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        regphp.setText("Register..!!");
        regphp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regphpActionPerformed(evt);
            }
        });
        getContentPane().add(regphp);
        regphp.setBounds(394, 360, 120, 25);

        jPanel1.setLayout(null);

        view_count.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        view_count.setText("View Count");
        view_count.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_countActionPerformed(evt);
            }
        });
        jPanel1.add(view_count);
        view_count.setBounds(240, 400, 120, 25);

        jButton1.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(433, 30, 100, 25);

        jLabel15.setIcon(new javax.swing.ImageIcon("F:\\CT Project\\Images\\tech.jpg")); // NOI18N
        jLabel15.setText("jLabel15");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(0, 0, 587, 440);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "JAVA", "VB.NET", "ORACLE", "PHP"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(0, 442, 587, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 590, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regjavaActionPerformed
        // TODO add your handling code here:
        JavaPay p=new JavaPay();
        p.setVisible(true);
        Home h=new Home();
        h.setVisible(false);
        dispose();
    }//GEN-LAST:event_regjavaActionPerformed

    private void regvbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regvbActionPerformed
        // TODO add your handling code here:
        VbPay p=new VbPay();
        p.setVisible(true);
        Home h=new Home();
        h.setVisible(false);
        dispose();
    }//GEN-LAST:event_regvbActionPerformed

    private void regoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regoraActionPerformed
        // TODO add your handling code here:
        OraclePay p=new OraclePay();
        p.setVisible(true);
        Home h=new Home();
        h.setVisible(false);
        dispose();
    }//GEN-LAST:event_regoraActionPerformed

    private void regphpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regphpActionPerformed
        // TODO add your handling code here:
        PhpPay p=new PhpPay();
        p.setVisible(true);
        Home h=new Home();
        h.setVisible(false);
        dispose();
    }//GEN-LAST:event_regphpActionPerformed

    private void view_countActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_countActionPerformed
        // TODO add your handling code here:
        try{

            Statement st = conn.createStatement();
            String sql="SELECT * FROM count";
            PST=conn.prepareStatement(sql);
            
            RS=PST.executeQuery();
            DefaultTableModel tm=(DefaultTableModel)jTable3.getModel();
            tm.setRowCount(0);
            while(RS.next()){
            Object o[]={RS.getString("java"),RS.getString("vb"),RS.getString("oracle"),RS.getString("php")};
            tm.addRow(o);
            }
        } 
        catch (Exception e)
    {
      System.err.println(e.getMessage());
    }
    }//GEN-LAST:event_view_countActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login s=new Login();
        s.setVisible(true);
        Home v=new Home();
        v.setVisible(false);
        dispose();
       JOptionPane.showMessageDialog(null,"LOGGED OUT SUCCESSFULLY");

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton regjava;
    private javax.swing.JButton regora;
    private javax.swing.JButton regphp;
    private javax.swing.JButton regvb;
    private javax.swing.JButton view_count;
    // End of variables declaration//GEN-END:variables
}
